### ISSUE TITLE
NullPointerException at SinkUser#equals()

### ISSUE THREAD

**Issue by Trojaner25** [Static-Interface/Sink-Plugins#4]
```
[21:28:40 WARN]: java.lang.NullPointerException
[21:28:40 WARN]:        at de.static_interface.sinklibrary.api.user.SinkUser.equals(SinkUser.java:91)
[21:28:40 WARN]:        at java.util.ArrayList.indexOf(ArrayList.java:317)
[21:28:40 WARN]:        at java.util.ArrayList.contains(ArrayList.java:300)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.corporation.Corporation.isCoCeo(Corporation.java:206)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.corporation.Corporation.getMembers(Corporation.java:163)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.commands.CorporationCommand.sendCorporationInfo(CorporationCommand.java:579)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.commands.CorporationCommand.onExecute(CorporationCommand.java:66)
[21:28:40 WARN]:        at de.static_interface.sinklibrary.api.command.SinkCommand$1.run(SinkCommand.java:123)
[21:28:40 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:28:40 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
```

**Comment by Diar1999** [comment]
Nicht gut

Von meinem Windows Phone gesendet
________________________________
Von: Trojaner<mailto:notifications@github.com>
Gesendet: ‎13.‎02.‎2015 21:34
An: Static-Interface/Sink-Plugins<mailto:Sink-Plugins@noreply.github.com>
Betreff: [Sink-Plugins] NullPointerException at SinkUser#equals() (#4)

```
[21:28:40 WARN]: java.lang.NullPointerException
[21:28:40 WARN]:        at de.static_interface.sinklibrary.api.user.SinkUser.equals(SinkUser.java:91)
[21:28:40 WARN]:        at java.util.ArrayList.indexOf(ArrayList.java:317)
[21:28:40 WARN]:        at java.util.ArrayList.contains(ArrayList.java:300)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.corporation.Corporation.isCoCeo(Corporation.java:206)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.corporation.Corporation.getMembers(Corporation.java:163)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.commands.CorporationCommand.sendCorporationInfo(CorporationCommand.java:579)
[21:28:40 WARN]:        at de.static_interface.reallifeplugin.commands.CorporationCommand.onExecute(CorporationCommand.java:66)
[21:28:40 WARN]:        at de.static_interface.sinklibrary.api.command.SinkCommand$1.run(SinkCommand.java:123)
[21:28:40 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:28:40 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[21:28:40 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
```

---
Reply to this email directly or view it on GitHub:
https://github.com/Static-Interface/Sink-Plugins/issues/4

**Comment by rinukkusu** [comment]
>Von meinem Windows Phone gesendet
